import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {buildOffice,optimizeOffice,office,obstacles,stations,seats,doors,powerScreen} from './office.js';
import {people,loadCharacter,animateCharacter} from './characters.js';
import {pathfind} from './nav.js';
import {MAX_VISIBLE,visualState,describe,chooseAvatar,validSnapshot} from './live-state.js';
const $=id=>document.getElementById(id),mount=$('scene');
const scene=new T.Scene();scene.background=new T.Color('#e6e9df');
const camera=new T.OrthographicCamera(-10,10,10,-10,.1,150);
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true});}catch(e){$('load-text').textContent='WebGL2 tidak tersedia. Gunakan browser dengan akselerasi grafis aktif.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;mount.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minZoom=.65;controls.maxZoom=3.5;controls.minPolarAngle=.4;controls.maxPolarAngle=1.2;controls.mouseButtons={LEFT:null,MIDDLE:T.MOUSE.PAN,RIGHT:T.MOUSE.ROTATE};controls.touches={ONE:null,TWO:T.TOUCH.DOLLY_PAN};
function resize(){const a=mount.clientWidth/mount.clientHeight,v=Math.max(15.3,18.8/a);camera.left=-v*a/2;camera.right=v*a/2;camera.top=v/2;camera.bottom=-v/2;camera.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight);}
function resetCamera(){camera.position.set(18,18,18);controls.target.set(0,0,0);camera.zoom=1;controls.update();resize();}
resetCamera();addEventListener('resize',resize);
scene.add(new T.HemisphereLight('#fff5da','#819b90',2.1));const sun=new T.DirectionalLight('#fff1d4',3.2);sun.position.set(-6,15,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});sun.shadow.normalBias=.025;sun.shadow.bias=-.0002;scene.add(sun);const fill=new T.DirectionalLight('#cde2ed',1.3);fill.position.set(5,8,-8);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#e6e9df',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.49;ground.receiveShadow=true;scene.add(ground);buildOffice();scene.add(office);optimizeOffice();
const ring=new T.Mesh(new T.RingGeometry(.33,.39,36),new T.MeshBasicMaterial({color:'#cce793',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.065;ring.visible=false;scene.add(ring);
const actors=new Map(),roster=new Map(),loading=new Set(),loadErrors=new Set(),pickable=[];
const seatPool=[...stations.map(s=>s.seat),...seats.filter(s=>!s.station).slice(0,6)];
let snapshot={agents:[],events:[]},selected=null,paused=false,connected=false,sound=false,audio=null,clock=0,previous=0,polling=false,noticeTimer=0;
let seenWaiting=new Set(),seenDone=new Set();
function notify(message){$('notice').hidden=false;$('notice').textContent=message;noticeTimer=7;}
function ping(){if(!sound||!audio)return;const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.connect(gain);gain.connect(audio.destination);oscillator.frequency.value=740;gain.gain.setValueAtTime(.04,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);oscillator.start();oscillator.stop(audio.currentTime+.26);}
function choose(id){selected=id;for(const [key,r] of roster)r.button.setAttribute('aria-pressed',String(key===id));updatePanel();}
function focusSelected(){const c=actors.get(selected);if(!c)return;const offset=new T.Vector3().subVectors(camera.position,controls.target);controls.target.copy(c.root.position);controls.target.y=.7;camera.position.copy(controls.target).add(offset);camera.zoom=1.75;camera.updateProjectionMatrix();}
function updatePanel(){const a=snapshot.agents.find(a=>a.id===selected);$('selected-name').textContent=a?.label||'Belum ada sesi';$('status').textContent=a?(connected?describe(a):'Koneksi terputus · status terakhir'):'Kantor siap';$('tool').textContent=a?.tool|| (a?describe(a):'—');$('detail').textContent=a?(a.approval?'Jawab permintaan persetujuan di Hermes.':a.outcome==='error'?'Tool terakhir gagal; periksa sesi Hermes.':a.parent?'Subagent dari '+a.parent.slice(-12):a.platform||'Hermes Agent'):'Aktivitas nyata akan muncul otomatis.';$('focus-agent').disabled=!actors.has(selected);$('completed').textContent=String(snapshot.tools_completed||0).padStart(2,'0');$('waiting').textContent=String(snapshot.waiting||0).padStart(2,'0');if(a){const p=people[chooseAvatar(a.id)];$('selected-avatar').style.background=p.color;$('selected-avatar').textContent=a.kind==='subagent'?'↳':'☤';}ring.visible=actors.has(selected)&&actors.get(selected).root.visible;}
function updateRoster(){const ids=new Set(snapshot.agents.map(a=>a.id));for(const [id,r] of roster){if(!ids.has(id)){r.button.remove();roster.delete(id);}}
 for(const a of snapshot.agents){let r=roster.get(a.id);if(!r){const button=document.createElement('button');button.className='person';const swatch=document.createElement('span');swatch.className='swatch';swatch.style.background=people[chooseAvatar(a.id)].color;swatch.textContent=a.kind==='subagent'?'↳':'☤';const text=document.createElement('span'),name=document.createElement('strong'),status=document.createElement('small');text.append(name,status);button.append(swatch,text);button.onclick=()=>choose(a.id);button.setAttribute('aria-pressed','false');$('team').append(button);r={button,name,status};roster.set(a.id,r);}r.name.textContent=a.label;r.status.textContent=describe(a)+(loadErrors.has(a.id)?' · model gagal':!actors.has(a.id)&&!['gone','done'].includes(a.status)?' · antre visual':'');r.button.className='person'+(a.id===selected?' active':'')+(a.approval?' waiting':'')+(a.kind==='subagent'?' subagent':'');r.button.setAttribute('aria-pressed',String(a.id===selected));}
 if(!ids.has(selected))selected=snapshot.agents[0]?.id||null;
 $('agent-count').textContent=String(ids.size).padStart(2,'0');$('empty').hidden=ids.size>0;const live=snapshot.agents.filter(a=>!['gone','done'].includes(a.status));$('summary').textContent=live.length?`${live.length} agent · ${snapshot.waiting||0} perlu persetujuan`:'Menunggu sesi Hermes.';$('capacity').textContent=live.length>MAX_VISIBLE?`${MAX_VISIBLE} karakter · ${live.length-MAX_VISIBLE} antre visual`:'6 meja + 6 kursi rapat';
 const e=snapshot.events?.[0];$('last-event').textContent=e?`${e.label} · ${e.tool||e.event.replaceAll('_',' ')}`:'Tidak ada aktivitas';updatePanel();}
function reserveSeat(excludeId=null){const used=new Set([...actors.values()].filter(c=>!c.exitComplete&&c.id!==excludeId).map(c=>c.seat));return seatPool.find(s=>!used.has(s));}
function route(c,to,mode){const path=pathfind(c.root.position,to,obstacles);if(path){c.path=path;c.motion=mode;c.state='walking';return true;}c.motion='blocked';c.path=[];return false;}
async function spawn(a){if(loadErrors.has(a.id)||loading.has(a.id)||actors.has(a.id)||['done','gone'].includes(a.status))return;const seat=reserveSeat();if(!seat)return;loading.add(a.id);
 try{const p=people[chooseAvatar(a.id)],c=await loadCharacter({...p,start:[1.45,5.1],station:seatPool.indexOf(seat)});const latest=snapshot.agents.find(x=>x.id===a.id);if(!latest||['done','gone'].includes(latest.status))return;
 c.id=a.id;c.agent=latest;c.seat=seat;c.motion='arriving';c.exitComplete=false;c.finishedAt=null;scene.add(c.root);actors.set(a.id,c);
 const label=document.createElement('div');label.className='agent-label';$('labels').append(label);c.label=label;
 const pick=new T.Mesh(new T.BoxGeometry(.65,1.7,.65),new T.MeshBasicMaterial({visible:false}));pick.position.y=.85;pick.userData.actor=a.id;c.root.add(pick);pickable.push(pick);c.pick=pick;
 c.book=new T.Mesh(new T.BoxGeometry(.32,.06,.25),new T.MeshStandardMaterial({color:'#dfc483'}));c.book.position.set(0,.93,.24);c.book.visible=false;c.root.add(c.book);
 doors[2].open=true;route(c,seat,'arriving');if(!selected)selected=a.id;
 }catch(error){loadErrors.add(a.id);console.error('Character asset could not load',error);notify('Model karakter gagal dimuat. Muat ulang halaman untuk mencoba lagi.');}finally{loading.delete(a.id);}}
function remove(c){if(c.seat?.station)powerScreen(c.seat.station,false);scene.remove(c.root);c.label.remove();const i=pickable.indexOf(c.pick);if(i>=0)pickable.splice(i,1);c.root.traverse(o=>{if(o.isMesh)o.geometry.dispose();});actors.delete(c.id);}
async function syncActors(){
 const visible=new Map(snapshot.agents.map(a=>[a.id,a]));for(const c of actors.values()){const a=visible.get(c.id);c.agent=a||{...c.agent,status:'gone',approval:false};if(c.exitComplete&&!a)remove(c);}
 // Sequential loads also reserve seats deterministically during bursts.
 for(const a of snapshot.agents){if([...actors.values()].filter(c=>!c.exitComplete).length>=MAX_VISIBLE)break;await spawn(a);}
 updateRoster();}
async function poll(){if(polling)return;polling=true;try{const response=await fetch('/state',{cache:'no-store',signal:AbortSignal.timeout(4500)});if(!response.ok)throw Error('state unavailable');const data=await response.json();if(!validSnapshot(data))throw Error('incompatible service');snapshot=data;connected=true;$('connection').textContent='TERHUBUNG';$('connection-dot').classList.remove('offline');$('mode').hidden=data.mode!=='demo';
 const waiting=new Set(data.agents.filter(a=>a.approval).map(a=>a.id));const done=new Set(data.agents.filter(a=>a.status==='done').map(a=>a.id));if([...waiting].some(id=>!seenWaiting.has(id))||[...done].some(id=>!seenDone.has(id)))ping();seenWaiting=waiting;seenDone=done;
 if(waiting.size){$('notice').hidden=false;$('notice').textContent=`${waiting.size} agent menunggu persetujuan. Jawab di Hermes untuk melanjutkan.`;noticeTimer=2;}
 await syncActors();
 }catch(error){connected=false;$('connection').textContent='TERPUTUS';$('connection-dot').classList.add('offline');$('summary').textContent='Mencoba menghubungkan ulang…';updatePanel();}finally{polling=false;setTimeout(poll,1000);}}
function applyPose(c,dt,t){const v=visualState(c.agent);if(c.motion==='seated'){c.state=['typing','terminal','browsing','working','delegating'].includes(v)?'working':'sitting';if(c.seat.station){powerScreen(c.seat.station,!['idle','leaving'].includes(v));c.seat.station.screen.material.color.set(v==='terminal'?'#99e6b2':v==='waiting'?'#efbf88':'#ffffff');}}
 animateCharacter(c,dt,t);c.book.visible=c.motion==='seated'&&v==='reading';if(c.motion==='seated'&&v==='reading'){for(const l of Object.values(c.limbs)){l.arm.rotation.x=T.MathUtils.damp(l.arm.rotation.x,-1,8,dt);l.fore.rotation.x=T.MathUtils.damp(l.fore.rotation.x,-1.2,8,dt);}}if(c.motion==='seated'&&v==='waiting'){c.limbs.r.arm.rotation.x=T.MathUtils.damp(c.limbs.r.arm.rotation.x,-2.2,8,dt);c.limbs.r.fore.rotation.x=-.25;}if(c.motion==='seated'&&v==='delegating')c.limbs.r.arm.rotation.x=-1.5+Math.sin(t*3)*.14;
}
function updateActor(c,dt,t){const v=visualState(c.agent);
 if(v==='leaving'&&!['leaving','exited'].includes(c.motion)){if(c.finishedAt===null)c.finishedAt=t;if(t-c.finishedAt>3){if(c.seat.station)powerScreen(c.seat.station,false);route(c,{x:1.45,z:5.25},'leaving');}}
 if(v!=='leaving'&&c.exitComplete){c.exitComplete=false;c.root.visible=true;c.finishedAt=null;const seat=reserveSeat(c.id);if(seat)c.seat=seat;route(c,c.seat,'arriving');}
 if(c.path.length){const p=c.path[0],dx=p.x-c.root.position.x,dz=p.z-c.root.position.z,dist=Math.hypot(dx,dz);let hold=false;for(const d of doors){if(Math.hypot(c.root.position.x-d.x,c.root.position.z-d.z)<1.0&&Math.abs(p.x-d.x)<.9&&Math.abs(p.z-d.z)<.55){d.open=true;d.hold=1.5;if(Math.abs(d.angle)<1)hold=true;}}if(!hold){const move=dt*1.75;if(dist<=move){c.root.position.x=p.x;c.root.position.z=p.z;c.path.shift();}else{c.root.position.x+=dx/dist*move;c.root.position.z+=dz/dist*move;}if(dist>.001)c.root.rotation.y=Math.atan2(dx,dz);}}
 else if(c.motion==='arriving'){c.motion='seated';c.root.position.set(c.seat.x,0,c.seat.z);c.root.rotation.y=c.seat.angle;}
 else if(c.motion==='leaving'){c.motion='exited';c.exitComplete=true;c.root.visible=false;c.label.hidden=true;}
 applyPose(c,dt,t);
}
const projection=new T.Vector3();function labels(){const r=renderer.domElement.getBoundingClientRect();for(const c of actors.values()){c.label.hidden=!c.root.visible;projection.copy(c.root.position);projection.y+=1.82;projection.project(camera);if(projection.z>1){c.label.hidden=true;continue;}c.label.style.left=(r.left+(projection.x+1)*r.width/2)+'px';c.label.style.top=(r.top+(1-projection.y)*r.height/2)+'px';c.label.textContent=(c.agent.approval?'! ':c.agent.kind==='subagent'?'↳ ':'')+c.agent.label.slice(0,23);c.label.className='agent-label'+(c.agent.approval?' waiting':'')+(c.agent.kind==='subagent'?' subagent':'')+(c.id===selected?' selected':'');}}
const ray=new T.Raycaster(),mouse=new T.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||!down)return;const moved=Math.hypot(e.clientX-down[0],e.clientY-down[1]);down=null;if(moved>6)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const h=ray.intersectObjects(pickable.filter(p=>p.parent.visible),false)[0];if(h)choose(h.object.userData.actor);});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
$('reset-camera').onclick=resetCamera;$('zoom-in').onclick=()=>{camera.zoom=Math.min(3.5,camera.zoom*1.18);camera.updateProjectionMatrix();};$('zoom-out').onclick=()=>{camera.zoom=Math.max(.65,camera.zoom/1.18);camera.updateProjectionMatrix();};$('focus-agent').onclick=focusSelected;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Lanjutkan animasi':'Jeda animasi');};$('sound').onclick=async()=>{sound=!sound;if(sound){audio ||= new AudioContext();await audio.resume();}try{localStorage.setItem('virtue-sound',String(sound));}catch{}$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Matikan suara notifikasi':'Aktifkan suara notifikasi');};
$('loading').style.opacity=0;setTimeout(()=>$('loading')?.remove(),500);poll();
renderer.setAnimationLoop(stamp=>{const dt=Math.min((stamp-previous)/1000||0,.05);previous=stamp;if(!paused){clock+=dt;for(const c of actors.values())updateActor(c,dt,clock);for(const d of doors){d.hold=Math.max(0,(d.hold||0)-dt);if(d.hold===0&&!([...actors.values()].some(c=>Math.hypot(c.root.position.x-d.x,c.root.position.z-d.z)<1.1)))d.open=false;d.angle=T.MathUtils.damp(d.angle,d.open?-Math.PI*.53:0,7,dt);d.hinge.rotation.y=d.angle;}}
 controls.update();const chosen=actors.get(selected);if(chosen){ring.visible=chosen.root.visible;ring.position.x=chosen.root.position.x;ring.position.z=chosen.root.position.z;ring.material.color.set(chosen.agent.approval?'#d78b48':'#cce793');}else ring.visible=false;labels();noticeTimer-=dt;if(noticeTimer<0)$('notice').hidden=true;$('clock').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});renderer.render(scene,camera);});
