import * as T from 'three';
import {GLTFExporter} from './vendor/GLTFExporter.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {buildOffice,optimizeOffice,office,obstacles,stations,seats,doors,targets,powerScreen} from './office.js';
import {people,loadCharacter,animateCharacter} from './characters.js';
import {pathfind,blocked} from './nav.js';
const $=id=>document.getElementById(id),mount=$('scene');
const scene=new T.Scene();scene.background=new T.Color('#e6e9df');
const camera=new T.OrthographicCamera(-10,10,10,-10,.1,150);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;mount.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=true;controls.enableRotate=true;controls.minZoom=.7;controls.maxZoom=2.8;controls.minPolarAngle=.40;controls.maxPolarAngle=1.2;controls.mouseButtons={LEFT:null,MIDDLE:T.MOUSE.PAN,RIGHT:T.MOUSE.ROTATE};controls.touches={ONE:null,TWO:T.TOUCH.DOLLY_PAN};
function resetCamera(){camera.position.set(18,18,18);controls.target.set(0,.0,0);camera.zoom=1;controls.update();resize();}
function resize(){const w=mount.clientWidth,h=mount.clientHeight,a=w/h;const view=Math.max(15.3,18.8/a);camera.left=-view*a/2;camera.right=view*a/2;camera.top=view/2;camera.bottom=-view/2;camera.updateProjectionMatrix();renderer.setSize(w,h);}
resetCamera();window.addEventListener('resize',resize);
scene.add(new T.HemisphereLight('#fff5da','#819b90',2.1));const sun=new T.DirectionalLight('#fff1d4',3.2);sun.position.set(-6,15,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=10;sun.shadow.camera.bottom=-10;sun.shadow.normalBias=.025;sun.shadow.bias=-.0002;scene.add(sun);const fill=new T.DirectionalLight('#cde2ed',1.3);fill.position.set(5,8,-8);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#e6e9df',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.49;ground.receiveShadow=true;scene.add(ground);buildOffice();scene.add(office);optimizeOffice();
const ring=new T.Mesh(new T.RingGeometry(.33,.38,40),new T.MeshBasicMaterial({color:'#cce793',side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.065;scene.add(ring);
const destination=new T.Mesh(new T.RingGeometry(.13,.18,24),new T.MeshBasicMaterial({color:'#ebf9ae',side:T.DoubleSide,transparent:true,opacity:.8}));destination.rotation.x=-Math.PI/2;destination.visible=false;scene.add(destination);
let chars=[],active=0,paused=false,simTime=0,toastAge=0,lastStamp=0;const keys=new Set();
function toast(text){$('toast').textContent=text;$('toast').style.opacity='1';toastAge=0;}
function select(i){if(!chars[i])return;active=i;document.querySelectorAll('.person').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',j===i?'true':'false');});$('selected-name').textContent=chars[i].name+' / '+chars[i].role;$('selected-avatar').textContent=String(i+1).padStart(2,'0');$('selected-avatar').style.background=chars[i].color;updateUI();}
function release(c){if(c.seat){c.seat.occupied=null;c.seat=null;}c.pending=null;c.path=[];c.state='idle';}
function nearestDoor(c){return [...doors].sort((a,b)=>Math.hypot(a.x-c.root.position.x,a.z-c.root.position.z)-Math.hypot(b.x-c.root.position.x,b.z-c.root.position.z))[0];}
function toggleDoor(d){if(d.open&&chars.some(c=>Math.hypot(c.root.position.x-d.x,c.root.position.z-d.z)<.8)){toast('Ada karakter di ambang pintu. Geser dahulu sebelum menutup.');return;}d.open=!d.open;toast(d.label+(d.open?' dibuka.':' ditutup.'));}
function go(c,point,action=null){const path=pathfind(c.root.position,point,obstacles);if(!path){toast('Tujuan terhalang. Pilih lantai kosong atau objek lain.');return false;}release(c);c.path=path;c.pending=action;c.state='walking';destination.position.set(point.x,.07,point.z);destination.visible=true;return true;}
function approachSeat(c,s,kind){if(s.occupied&&s.occupied!==c){toast('Kursi sedang digunakan '+s.occupied.name+'. Pilih kursi lain.');return;}if(c.seat===s){finish(c,{kind,seat:s});return;}go(c,{x:s.x,z:s.z},{kind,seat:s});}
function finish(c,action){if(!action){c.state='idle';return;}if(action.kind==='door'){c.state='idle';c.root.rotation.y=Math.atan2(action.door.x-c.root.position.x,action.door.z-c.root.position.z);toggleDoor(action.door);return;}const s=action.seat;if(s.occupied&&s.occupied!==c){c.state='idle';toast('Kursi baru saja ditempati karakter lain.');return;}c.seat=s;s.occupied=c;c.root.position.set(s.x,0,s.z);c.root.rotation.y=s.angle;c.state='sitting';const station=s.station;
 if(action.kind==='power'&&station){powerScreen(station,!station.on);c.state=station.on?'booting':'sitting';c.bootTime=0;c.afterBoot='sitting';toast(station.label+': komputer '+(station.on?'dinyalakan.':'dimatikan.'));}
 if(action.kind==='work'&&station){c.progress=0;if(!station.on){powerScreen(station,true);c.state='booting';c.bootTime=0;c.afterBoot='working';toast(c.name+' menyalakan komputer sebelum bekerja.');}else{c.state='working';toast(c.name+' sedang mengerjakan tugas.');}}
}
function command(kind,data=null){const c=chars[active];if(!c)return;if(kind==='stand'){release(c);toast(c.name+' berdiri. Klik lantai untuk berjalan.');return;}if(kind==='door'){const d=data||nearestDoor(c);const side=c.root.position.z>d.z?1:-1;go(c,{x:d.x,z:Math.max(-5.3,Math.min(5.2,d.z+side*.72))},{kind:'door',door:d});return;}
 const current=(kind==='power'||kind==='work')?(c.seat?.station?c.seat:null):c.seat;const s=data?.seat||data||current||stations[c.station].seat;approachSeat(c,s,kind);}
function clickTarget(target){if(target.kind==='character'){select(target.data);return;}if(target.kind==='door')command('door',target.data);else if(target.kind==='seat')command('sit',target.data);else if(target.kind==='power')command('power',target.data);else if(target.kind==='station')command('work',target.data);}
const stateLabels={idle:'Siap bergerak',walking:'Berjalan ke tujuan',sitting:'Duduk',working:'Mengerjakan tugas',booting:'Menyalakan komputer'};
function updateUI(){const c=chars[active];if(!c)return;$('status').textContent=paused?'Simulasi dijeda':stateLabels[c.state];$('completed').textContent=String(chars.reduce((n,c)=>n+c.done,0)).padStart(2,'0');$('progress').style.width=(c.progress/12*100)+'%';document.querySelectorAll('.person small').forEach((el,i)=>el.textContent=stateLabels[chars[i].state]);}
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0),point=new T.Vector3();let down=null;
function pick(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(targets,false)[0];}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down={x:e.clientX,y:e.clientY};});
renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||!down)return;const moved=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(moved>6||!chars.length)return;const hit=pick(e);if(hit){clickTarget(hit.object.userData.target);return;}if(ray.ray.intersectPlane(plane,point))go(chars[active],point);});
renderer.domElement.addEventListener('pointermove',e=>{const hit=pick(e);$('tooltip').hidden=!hit;if(hit){$('tooltip').textContent=hit.object.userData.target.label;$('tooltip').style.left=Math.min(e.clientX+15,innerWidth-230)+'px';$('tooltip').style.top=(e.clientY-34)+'px';}renderer.domElement.style.cursor=hit?'pointer':'crosshair';});renderer.domElement.addEventListener('pointerleave',()=>{$('tooltip').hidden=true;});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>command(b.dataset.action);
$('reset-camera').onclick=resetCamera;$('zoom-in').onclick=()=>{camera.zoom=Math.min(2.8,camera.zoom*1.18);camera.updateProjectionMatrix();};$('zoom-out').onclick=()=>{camera.zoom=Math.max(.7,camera.zoom/1.18);camera.updateProjectionMatrix();};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Lanjutkan simulasi':'Jeda simulasi');updateUI();};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if('12345'.includes(k)&&k.length===1)select(+k-1);if(k==='e'){const c=chars[active];if(!c)return;const nearby=targets.map(t=>({t,p:t.getWorldPosition(new T.Vector3())})).filter(v=>v.t.userData.target.kind!=='character').sort((a,b)=>a.p.distanceTo(c.root.position)-b.p.distanceTo(c.root.position));if(nearby[0])clickTarget(nearby[0].t.userData.target);}if(k==='escape')command('stand');});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
const forward=new T.Vector3(),right=new T.Vector3(),velocity=new T.Vector3();
function keyboard(c,dt){let z=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);if(!x&&!z)return false;release(c);camera.getWorldDirection(forward);forward.y=0;forward.normalize();right.crossVectors(forward,T.Object3D.DEFAULT_UP).normalize();velocity.copy(forward).multiplyScalar(z).addScaledVector(right,x).normalize();const nx=c.root.position.x+velocity.x*dt*1.8,nz=c.root.position.z+velocity.z*dt*1.8;let doorBlocked=false;for(const d of doors){if(Math.hypot(nx-d.x,nz-d.z)<.8){d.open=true;if(Math.abs(nz-d.z)<.25&&Math.abs(d.angle)<1)doorBlocked=true;}}if(!doorBlocked){if(!blocked(nx,c.root.position.z,obstacles))c.root.position.x=nx;if(!blocked(c.root.position.x,nz,obstacles))c.root.position.z=nz;}c.root.rotation.y=Math.atan2(velocity.x,velocity.z);c.state='walking';return true;}
function update(c,dt,t){const manual=c===chars[active]&&keyboard(c,dt);
 if(!manual&&c.state==='walking'){if(c.path.length){const p=c.path[0],dx=p.x-c.root.position.x,dz=p.z-c.root.position.z,dist=Math.hypot(dx,dz),step=dt*1.8;let wait=false;for(const d of doors){if(Math.hypot(c.root.position.x-d.x,c.root.position.z-d.z)<.82&&Math.abs(p.x-d.x)<.9&&Math.abs(p.z-d.z)<.55){d.open=true;if(Math.abs(d.angle)<1.0)wait=true;}}if(!wait){if(dist<=step){c.root.position.x=p.x;c.root.position.z=p.z;c.path.shift();}else{c.root.position.x+=dx/dist*step;c.root.position.z+=dz/dist*step;}if(dist>.001)c.root.rotation.y=Math.atan2(dx,dz);}}else{const action=c.pending;c.pending=null;finish(c,action);destination.visible=false;}}
 if(c.state==='booting'){c.bootTime+=dt;if(c.bootTime>1.4)c.state=c.afterBoot;}
 if(c.state==='working'){c.progress=Math.min(12,c.progress+dt);if(c.progress>=12){c.done++;c.state='sitting';toast('✓ '+c.name+' menyelesaikan satu tugas.');}}
 animateCharacter(c,dt,t);
}
async function init(){try{for(let i=0;i<people.length;i++){$('load-text').textContent='Menyiapkan '+people[i].name+'…';const c=await loadCharacter(people[i]);chars.push(c);scene.add(c.root);const h=new T.Mesh(new T.BoxGeometry(.70,1.62,.65),new T.MeshBasicMaterial({visible:false}));h.position.y=.8;c.root.add(h);h.userData.target={kind:'character',data:i,label:c.name+' · pilih karakter'};targets.push(h);}
 $('team').innerHTML=people.map((p,i)=>`<button class="person" aria-pressed="false" data-person="${i}"><span class="swatch" style="background:${p.color}">${String(i+1).padStart(2,'0')}</span><span><strong>${p.name}</strong><small>${p.role}</small></span><span class="key">${i+1}</span></button>`).join('');document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>select(+b.dataset.person));select(1);$('loading').style.opacity='0';setTimeout(()=>$('loading').remove(),500);
 // Expose serializable diagnostics for verification, without affecting gameplay.
 window.officeApp={get state(){return {active,paused,characters:chars.map(c=>({name:c.name,state:c.state,position:{x:c.root.position.x,z:c.root.position.z},done:c.done,progress:c.progress,seat:c.seat?.label})),doors:doors.map(d=>({label:d.label,open:d.open,angle:d.angle})),stations:stations.map(s=>({label:s.label,on:s.on})),drawCalls:renderer.info.render.calls}},select,command,go:(x,z)=>go(chars[active],{x,z}),scene,camera,renderer,chars,stations,doors,obstacles};
 }catch(error){console.error(error);$('load-text').textContent='Gagal memuat karakter. Jalankan aplikasi melalui MULAI.command atau npm start.';}}
init();
renderer.setAnimationLoop(stamp=>{const dt=Math.min((stamp-lastStamp)/1000||0,.05);lastStamp=stamp;if(!paused){simTime+=dt;for(const c of chars)update(c,dt,simTime);for(const d of doors){d.angle=T.MathUtils.damp(d.angle,d.open?-Math.PI*.53:0,7,dt);d.hinge.rotation.y=d.angle;}}controls.update();if(chars[active]){ring.position.x=chars[active].root.position.x;ring.position.z=chars[active].root.position.z;ring.scale.setScalar(1+Math.sin(stamp*.004)*.045);}toastAge+=dt;if(toastAge>7)$('toast').style.opacity='0';const minutes=Math.floor(simTime*2);$('clock').textContent=String(9+Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');if(Math.floor(stamp/150)!==Math.floor((stamp-dt*1000)/150))updateUI();renderer.render(scene,camera);});

$('snapshot').onclick=async()=>{const blob=await new Promise(resolve=>renderer.domElement.toBlob(resolve,'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Ruang_Preview.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Gambar kantor tersimpan.');};
$('export').onclick=async()=>{const b=$('export');b.disabled=true;try{const saved=[];scene.traverse(o=>{saved.push([o,o.userData,o.visible]);if(o.userData.target)o.visible=false;o.userData={};});const out=new T.Scene();out.name='Ruang Isometric Office';try{out.add(office.clone(true));for(const c of chars)out.add(c.root.clone(true));out.add(camera.clone());}finally{for(const [o,data,visible] of saved){o.userData=data;o.visible=visible;}}out.updateMatrixWorld(true);const buffer=await new GLTFExporter().parseAsync(out,{binary:true,onlyVisible:true});const blob=new Blob([buffer],{type:'model/gltf-binary'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Ruang_Office.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Model kantor 3D tersimpan. Bisa diimpor ke Blender.');}catch(e){console.error(e);toast('Ekspor belum berhasil. Silakan coba lagi.');}finally{b.disabled=false;}};
